#pragma once
#define HAVE_ATTRIBUTE_COLD 1
#define HAVE_ATTRIBUTE_NORETURN 1
#define HAVE_ATTRIBUTE_PRINTF 1
#define HAVE_ATTRIBUTE_CONST 1
#define HAVE_ATTRIBUTE_PURE 1
#define HAVE_ATTRIBUTE_UNUSED 1
#define HAVE_ATTRIBUTE_USED 1
#define HAVE_ATTRIBUTE_DEPRECATED 1
#define HAVE_ATTRIBUTE_NONNULL 1
#define HAVE_ATTRIBUTE_SENTINEL 1
#define HAVE_MEMMEM 1
#define HAVE_MEMRCHR 1
#define HAVE_WARN_UNUSED_RESULT 1
#define HAVE_BUILTIN_CPU_SUPPORTS 1
#define HAVE_BUILTIN_CONSTANT_P 1
#define HAVE_VALGRIND_MEMCHECK_H 1
#define HAVE_TYPEOF 1
