#! /bin/sh
src_dir="$1"
project_version="$2"
tag="$3"
output="$4"

if [ -z "$tag" ]; then
	version="$(git -C "$src_dir" describe --always --dirty=+ | sed 's/^gild-root-//')"
else
	version="$tag"
fi

mkdir -p "$(dirname "$p")"
cat >"$p" <<EOF
#pragma once
#define GILD_ROOT_VERSION $version
EOF
