#! /usr/bin/env bash
set -euf -o pipefail
src_dir="$1"
project_version="$2"
tag="$3"
output="$4"

if [ -z "$tag" ]; then
	version="$(git -C "$src_dir" describe --always --dirty=+ | sed 's/^gild-root-//')"
else
	version="$tag"
fi

cat >"$output" <<EOF
#pragma once
#define GILD_ROOT_VERSION $version
EOF
